name = "ios-install-qr"
main = "src/index.js"
compatibility_date = "2025-09-01"

workers_dev = true

[[kv_namespaces]]
binding = "QR_TOKENS"
# id заполняется после создания неймспейса: wrangler kv namespace create QR_TOKENS
id = ""